[package]
name = "downloader_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
reqwest = { version = "0.11", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
bytes = { version = "1.6.0"}
futures = "0.3"
futures-util = "0.3"
indicatif = "0.17.8"